### ISSUE TITLE
canceling ongoing sync operation causes crash

### ISSUE THREAD

**Issue by itswisdomagain** [raedahgroup/godcr-old#253]
If you cancel a sync op a few seconds after it starts, the following crash is gotten

```
unexpected fault address 0xb000000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb000000 pc=0x4581f4a]

goroutine 53 [running]:
runtime.throw(0x4b347d0, 0x5)
	/usr/local/go/src/runtime/panic.go:608 +0x72 fp=0xc000347588 sp=0xc000347558 pc=0x402dd02
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:397 +0x275 fp=0xc0003475d8 sp=0xc000347588 pc=0x4042f85
github.com/boltdb/bolt.(*DB).page(...)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/db.go:796
github.com/boltdb/bolt.(*Tx).page(...)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:578
github.com/boltdb/bolt.(*Bucket).pageNode(0xc0021117b8, 0x1059, 0xc0003477c0, 0xc000eda61f)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:726 +0xaa fp=0xc000347648 sp=0xc0003475d8 pc=0x4581f4a
github.com/boltdb/bolt.(*Cursor).search(0xc0003477c8, 0x544625c, 0x6, 0x6, 0x1059)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:254 +0x50 fp=0xc0003476f0 sp=0xc000347648 pc=0x45833a0
github.com/boltdb/bolt.(*Cursor).seek(0xc0003477c8, 0x544625c, 0x6, 0x6, 0x0, 0x0, 0xc000eda5f4, 0x4967340, 0xc000eda614, 0x4946080, ...)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/cursor.go:159 +0xa5 fp=0xc000347740 sp=0xc0003476f0 pc=0x4582cb5
github.com/boltdb/bolt.(*Bucket).Bucket(0xc0021117b8, 0x544625c, 0x6, 0x6, 0x49514c0)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/bucket.go:112 +0xe6 fp=0xc0003477f8 sp=0xc000347740 pc=0x457ec26
github.com/boltdb/bolt.(*Tx).Bucket(0xc0021117a0, 0x544625c, 0x6, 0x6, 0xc000eda674)
	/Users/itswisdomagain/go/pkg/mod/github.com/boltdb/bolt@v1.3.1/tx.go:101 +0x4f fp=0xc000347830 sp=0xc0003477f8 pc=0x458d06f
github.com/decred/dcrwallet/wallet/internal/bdb.(*transaction).ReadWriteBucket(0xc002158bf8, 0x544625c, 0x6, 0x6, 0x0, 0x0)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/internal/bdb/db.go:50 +0x4c fp=0xc000347868 sp=0xc000347830 pc=0x459276c
github.com/decred/dcrwallet/wallet/internal/bdb.(*transaction).ReadBucket(0xc002158bf8, 0x544625c, 0x6, 0x6, 0x0, 0xc000ed89c0)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/internal/bdb/db.go:46 +0x49 fp=0xc0003478a8 sp=0xc000347868 pc=0x45926c9
github.com/decred/dcrwallet/wallet/udb.(*Store).GetBlockHeader(0xc0000ac8d0, 0x4d7b480, 0xc002158bf8, 0xc000eda5b4, 0xc000eda5b0, 0x0, 0x0)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/udb/txmined.go:812 +0x6d fp=0xc000347938 sp=0xc0003478a8 pc=0x44a04ad
github.com/decred/dcrwallet/wallet.(*Wallet).nextRequiredPoWDifficulty(0xc0000b84e0, 0x4d7b480, 0xc002158bf8, 0xc00193c270, 0xc0017ee000, 0x7d0, 0x7d0, 0x0, 0xed31ab4a5, 0x54d9840, ...)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/difficulty.go:182 +0x32d fp=0xc000347ae8 sp=0xc000347938 pc=0x44e464d
github.com/decred/dcrwallet/wallet.(*Wallet).validateHeaderChainDifficulties(0xc0000b84e0, 0x4d7b480, 0xc002158bf8, 0xc0017ee000, 0x7d0, 0x7d0, 0x10f, 0xc002e80ca0, 0x402ca62, 0xc000310120, ...)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/difficulty.go:543 +0x1f4 fp=0xc000347c38 sp=0xc000347ae8 pc=0x44e67e4
github.com/decred/dcrwallet/wallet.(*Wallet).ValidateHeaderChainDifficulties.func1(0x4d7b480, 0xc002158bf8, 0x4d7b480, 0xc002158bf8)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/difficulty.go:510 +0x72 fp=0xc000347cb0 sp=0xc000347c38 pc=0x4511902
github.com/decred/dcrwallet/wallet/walletdb.View(0x4d834c0, 0xc00035a000, 0xc002e80d48, 0x0, 0x0)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/walletdb/interface.go:213 +0xbb fp=0xc000347d08 sp=0xc000347cb0 pc=0x445b95b
github.com/decred/dcrwallet/wallet.(*Wallet).ValidateHeaderChainDifficulties(0xc0000b84e0, 0xc0017ee000, 0x7d0, 0x7d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/wallet@v1.3.0/difficulty.go:508 +0xc3 fp=0xc000347d90 sp=0xc000347d08 pc=0x44e6593
github.com/decred/dcrwallet/chain.(*RPCSyncer).startupSync(0xc0001c70e0, 0x4d82a40, 0xc0000b64c0, 0x402ca62, 0x2efda1900000008)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/chain@v1.1.1/sync.go:539 +0x9cd fp=0xc000347f38 sp=0xc000347d90 pc=0x454547d
github.com/decred/dcrwallet/chain.(*RPCSyncer).Run.func1(0x189a2400000008, 0x4cb4068)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/chain@v1.1.1/sync.go:189 +0x89 fp=0xc000347f88 sp=0xc000347f38 pc=0x4546aa9
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0005be030, 0xc0005be060)
	/Users/itswisdomagain/go/pkg/mod/golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f/errgroup/errgroup.go:57 +0x57 fp=0xc000347fd0 sp=0xc000347f88 pc=0x44c8db7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000347fd8 sp=0xc000347fd0 pc=0x405b2e1
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/itswisdomagain/go/pkg/mod/golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f/errgroup/errgroup.go:54 +0x66

goroutine 1 [panicwait, locked to thread]:
runtime.gopark(0x0, 0x0, 0xc000001008, 0x1)
	/usr/local/go/src/runtime/proc.go:302 +0xeb
runtime.main()
	/usr/local/go/src/runtime/proc.go:220 +0x275
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1

goroutine 35 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 4 [chan receive]:
main.listenForInterruptRequests()
	/Users/itswisdomagain/go/src/github.com/raedahgroup/godcr/main.go:246 +0xdd
created by main.main
	/Users/itswisdomagain/go/src/github.com/raedahgroup/godcr/main.go:88 +0x164

goroutine 5 [runnable]:
os.Exit(0x0)
	/usr/local/go/src/os/proc.go:59 +0x4b
main.handleShutdown(0xc000465040)
	/Users/itswisdomagain/go/src/github.com/raedahgroup/godcr/main.go:274 +0xd2
created by main.main
	/Users/itswisdomagain/go/src/github.com/raedahgroup/godcr/main.go:89 +0x189

goroutine 51 [syscall]:
syscall.Syscall(0x3, 0x7, 0xc001556000, 0x80, 0xc0000b61c0, 0xc00003c500, 0x0)
	/usr/local/go/src/syscall/asm_darwin_amd64.s:16 +0x5
syscall.read(0x7, 0xc001556000, 0x80, 0x80, 0xc0000b6101, 0x0, 0x0)
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:947 +0x5a
syscall.Read(0x7, 0xc001556000, 0x80, 0x80, 0xc00008cf13, 0xc0002d0f10, 0x400e8ff)
	/usr/local/go/src/syscall/syscall_unix.go:172 +0x49
internal/poll.(*FD).Read(0xc0000c1320, 0xc001556000, 0x80, 0x80, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:165 +0x117
os.(*File).read(0xc0000be348, 0xc001556000, 0x80, 0x80, 0xc0000c1260, 0xc0002d0f40, 0xc0002d0f40)
	/usr/local/go/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc0000be348, 0xc001556000, 0x80, 0x80, 0x80, 0x80, 0x0)
	/usr/local/go/src/os/file.go:108 +0x69
github.com/gdamore/tcell.(*tScreen).inputLoop(0xc0004a31e0)
	/Users/itswisdomagain/go/pkg/mod/github.com/gdamore/tcell@v1.1.1/tscreen.go:1309 +0xbb
created by github.com/gdamore/tcell.(*tScreen).Init
	/Users/itswisdomagain/go/pkg/mod/github.com/gdamore/tcell@v1.1.1/tscreen.go:176 +0x63a

goroutine 25 [semacquire]:
sync.runtime_Semacquire(0xc0005be040)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc0005be038)
	/usr/local/go/src/sync/waitgroup.go:130 +0x64
golang.org/x/sync/errgroup.(*Group).Wait(0xc0005be030, 0xc0005c0010, 0xc0005be030)
	/Users/itswisdomagain/go/pkg/mod/golang.org/x/sync@v0.0.0-20181108010431-42b317875d0f/errgroup/errgroup.go:40 +0x31
github.com/decred/dcrwallet/chain.(*RPCSyncer).Run(0xc0001c70e0, 0x4d82a40, 0xc0000b64c0, 0x3015f203699301, 0x559a7a00178178, 0x3e757dd037369ea)
	/Users/itswisdomagain/go/pkg/mod/github.com/decred/dcrwallet/chain@v1.1.1/sync.go:222 +0x5ee
github.com/raedahgroup/dcrlibwallet.(*LibWallet).RpcSync.func13(0xc0001c70e0, 0x4d82a40, 0xc0004a6cc0, 0xc00021f730)
	/Users/itswisdomagain/go/pkg/mod/github.com/raedahgroup/dcrlibwallet@v1.0.1-0.20190311225301-a7c6034624e9/dcrlibwallet.go:572 +0x5f
created by github.com/raedahgroup/dcrlibwallet.(*LibWallet).RpcSync
	/Users/itswisdomagain/go/pkg/mod/github.com/raedahgroup/dcrlibwallet@v1.0.1-0.20190311225301-a7c6034624e9/dcrlibwallet.go:568 +0x654
```

**Comment by itswisdomagain** [comment]
Only noticed with rpc sync on dcrlibwallet...

**Comment by itswisdomagain** [comment]
Should be fixed with latest update to dcrlibwallet

**Comment by itswisdomagain** [comment]
To add more context to the issue:
The crash happens when sync is canceled during the headers fetching stage and the wallet is immediately shutdown.

Resolved in https://github.com/raedahgroup/dcrlibwallet/pull/50/.
